services:
  bcr-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: jazzy
    image: bcr_bot:jazzy
    container_name: bcr-bot
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/root/ros2_ws/src/bcr_bot:rw
    stdin_open: true
    tty: true
