<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="new_bcr_robot">

<gazebo>
  <static>false</static>
</gazebo>


<!-- .....................MULTI WHEEL DIFF DRIVE ................................... -->

<gazebo>
	<plugin name="diffdrive_plugin_multiwheel" filename="libdiffdrive_plugin_multi_wheel.so">
		<robotNamespace></robotNamespace>
		<updateRate>100.0</updateRate>
		<leftJoints>back_left_wheel_joint front_left_wheel_joint</leftJoints>
		<rightJoints>back_right_wheel_joint front_right_wheel_joint</rightJoints>
		<wheelSeparation>${wheel_base}</wheelSeparation>
		<wheelDiameter>${2*wheel_radius}</wheelDiameter>
		<robotBaseFrame>base_link</robotBaseFrame>
		<torque>${wheel_torque}</torque>
		<commandTopic>/cmd_vel</commandTopic>
		<odometryTopic>odom</odometryTopic>
		<odometryFrame>odom</odometryFrame>
		<publishOdometryTf>true</publishOdometryTf>
		<publishOdometryMsg>true</publishOdometryMsg>
	</plugin>
</gazebo>

<gazebo>
	<plugin name="diffdrive_plugin_multiwheel_middle" filename="libdiffdrive_plugin_multi_wheel.so">
		<robotNamespace></robotNamespace>
		<updateRate>100.0</updateRate>
		<leftJoints>middle_left_wheel_joint</leftJoints>
		<rightJoints>middle_right_wheel_joint</rightJoints>
		<wheelSeparation>${wheel_middle_base}</wheelSeparation>
		<wheelDiameter>${2*wheel_radius}</wheelDiameter>
		<robotBaseFrame>base_link</robotBaseFrame>
		<torque>${wheel_torque}</torque>
		<commandTopic>/cmd_vel</commandTopic>
		<odometryTopic>odom</odometryTopic>
		<odometryFrame>odom</odometryFrame>
		<publishOdometryTf>true</publishOdometryTf>
		<publishOdometryMsg>true</publishOdometryMsg>
	</plugin>
</gazebo>


</robot>