<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="new_bcr_robot">

<gazebo>
  <static>false</static>
</gazebo>


<gazebo reference="back_left_wheel_joint">
  <mu1 value="${trolley_wheel_friction}"/>
  <mu2 value="${trolley_wheel_friction}"/>
  <kp  value="10000000.0" />
  <kd  value="1.0" />
  <fdir1 value="1 0 0"/>
</gazebo>

<gazebo reference="back_right_wheel_joint">
  <mu1 value="${trolley_wheel_friction}"/>
  <mu2 value="${trolley_wheel_friction}"/>
  <kp  value="10000000.0" />
  <kd  value="1.0" />
  <fdir1 value="1 0 0"/>
</gazebo>

<gazebo reference="front_left_wheel_joint">
  <mu1 value="${trolley_wheel_friction}"/>
  <mu2 value="${trolley_wheel_friction}"/>
  <kp  value="10000000.0" />
  <kd  value="1.0" />
  <fdir1 value="1 0 0"/>
</gazebo>

<gazebo reference="front_right_wheel_joint">
  <mu1 value="${trolley_wheel_friction}"/>
  <mu2 value="${trolley_wheel_friction}"/>
  <kp  value="10000000.0" />
  <kd  value="1.0" />
  <fdir1 value="1 0 0"/>
</gazebo>

<!-- .....................MULTI WHEEL DIFF DRIVE ................................... -->

<gazebo>
	<plugin name="diffdrive_plugin_multiwheel_middle" filename="libdiffdrive_plugin_multi_wheel.so">
		<robotNamespace></robotNamespace>
		<updateRate>100.0</updateRate>
		<leftJoints>middle_left_wheel_joint</leftJoints>
		<rightJoints>middle_right_wheel_joint</rightJoints>
		<wheelSeparation>${traction_wheel_base}</wheelSeparation>
		<wheelDiameter>${2*wheel_radius}</wheelDiameter>
		<robotBaseFrame>base_link</robotBaseFrame>
		<torque>${traction_wheel_torque}</torque>
		<commandTopic>/cmd_vel</commandTopic>
		<odometryTopic>odom</odometryTopic>
		<odometryFrame>odom</odometryFrame>
		<publishOdometryTf>true</publishOdometryTf>
		<publishOdometryMsg>true</publishOdometryMsg>
	</plugin>
</gazebo>

<!--............................... IMU PLUGIN ..................................... -->

<gazebo>
	<plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
			<updateRate>50.0</updateRate>
			<bodyName>base_link</bodyName>
			<topicName>/imu</topicName>
			<serviceName>/imu/calibrate</serviceName>
			<accelOffset>0.0 0.0 0.0</accelOffset>
			<accelDrift>0.0 0.0 0.0</accelDrift>
			<accelDriftFrequency>0.0 0.0 0.0</accelDriftFrequency>
			<accelGaussianNoise>0.0 0.0 0.0</accelGaussianNoise>
			<rateOffset>0.0 0.0 0.0</rateOffset>
			<rateDrift>0.0 0.0 0.0</rateDrift>
			<rateDriftFrequency>0.0 0.0 0.0</rateDriftFrequency>
			<rateGaussianNoise>0.0 0.0 0.0</rateGaussianNoise>
			<headingOffset>0.0</headingOffset>
			<headingDrift>0.0</headingDrift>
			<headingDriftFrequency>0.0</headingDriftFrequency>
			<headingGaussianNoise>0.0</headingGaussianNoise>
			<rpyOffset>0.0 0.0 0.0</rpyOffset>
			<xyzOffset>0.0 0.0 0.0</xyzOffset>
			<gaussianNoise>0.0</gaussianNoise>
			<frameName>imu_frame</frameName>
	</plugin>
</gazebo>

<!-- ........................... 2D LIDAR PLUGIN ................................... -->

<xacro:if value="$(arg two_d_lidar_enabled)">

   <gazebo reference="two_d_lidar">
      <gravity>true</gravity>
      <sensor type="ray" name="two_d_lidar">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>${two_d_lidar_update_rate}</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>${two_d_lidar_sample_size}</samples>
              <resolution>1</resolution>
              <min_angle>${radians(two_d_lidar_min_angle)}</min_angle>
              <max_angle>${radians(two_d_lidar_max_angle)}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>${two_d_lidar_min_range}</min>
            <max>${two_d_lidar_max_range}</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.001</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
          <topicName>scan</topicName>
          <frameName>two_d_lidar</frameName>
          <robotNamespace>/</robotNamespace>
        </plugin>
      </sensor>
   </gazebo>

</xacro:if>

<!--................................................................................. -->


</robot>