<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bcr_bot">

<!-- ........................... SENSOR PLUGIN ................................... -->

<gazebo>
    <plugin filename="ignition-gazebo-sensors-system" name="ignition::gazebo::systems::Sensors">
        <render_engine>ogre2</render_engine>
    </plugin>

    <plugin filename="ignition-gazebo-imu-system"
        name="ignition::gazebo::systems::Imu">
    </plugin>

    <plugin filename="ignition-gazebo-joint-state-publisher-system" 
        name="ignition::gazebo::systems::JointStatePublisher">
    </plugin>

<!-- ........................... DIFFERENTIAL DRIVE PLUGIN ................................... -->

    <plugin filename="ignition-gazebo-diff-drive-system" name="ignition::gazebo::systems::DiffDrive">
        <left_joint>middle_left_wheel_joint</left_joint>
        <right_joint>middle_right_wheel_joint</right_joint>
        <wheel_separation>${traction_wheel_base+traction_wheel_width-0.01}</wheel_separation>
        <wheel_radius>${traction_wheel_radius+0.01}</wheel_radius>
        <odom_publish_frequency>30</odom_publish_frequency>
        <topic>/cmd_vel</topic>
        <odom_topic>$(arg wheel_odom_topic)</odom_topic>
        <tf_topic>/tf</tf_topic>
        <frame_id>odom</frame_id>
        <child_frame_id>base_link</child_frame_id>
    </plugin>
</gazebo>

<!-- ........................... 2D LIDAR config ................................... -->

<xacro:if value="$(arg two_d_lidar_enabled)">
    <gazebo reference="two_d_lidar">
        <sensor name='gpu_lidar' type='gpu_lidar'>
            <topic>scan</topic>
            <update_rate>${two_d_lidar_update_rate}</update_rate>
            <ignition_frame_id>two_d_lidar</ignition_frame_id>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>${two_d_lidar_sample_size}</samples>
                        <resolution>1</resolution>
                        <min_angle>${radians(two_d_lidar_min_angle)}</min_angle>
                        <max_angle>${radians(two_d_lidar_max_angle)}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>${two_d_lidar_min_range}</min>
                    <max>${two_d_lidar_max_range}</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.001</stddev>
                </noise>
            </lidar>
            <alwaysOn>1</alwaysOn>
            <visualize>true</visualize>
        </sensor>
    </gazebo>
</xacro:if>

<!-- ........................... CAMERA config ................................... -->

<xacro:if value="$(arg camera_enabled)">
    <gazebo reference="kinect_camera">
        <sensor type="depth_camera" name="kinect_camera">
            <update_rate>30.0</update_rate>
            <topic>kinect_camera</topic>
            <ignition_frame_id>kinect_camera</ignition_frame_id>
            <camera_info_topic>camera_info</camera_info_topic>
            <camera>
                <horizontal_fov>${radians(camera_horizontal_fov)}</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
        </sensor>
    </gazebo>
</xacro:if>

<!-- ........................... IMU config ................................... -->

<gazebo reference="imu_frame">
    <sensor name="imu_sensor" type="imu">
        <always_on>1</always_on>
        <update_rate>1</update_rate>
        <ignition_frame_id>imu_frame</ignition_frame_id>
        <visualize>true</visualize>
        <topic>imu</topic>
    </sensor>
</gazebo> 

</robot>