<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="new_bcr_robot">

<!--................................ XACRO CONSTANTS .............................. -->

<xacro:property name="chassis_mass"                    		value="70"/>
<xacro:property name="chassis_length"                    	value="0.9"/>
<xacro:property name="chassis_width"                    	value="0.64"/>
<xacro:property name="chassis_height"                    	value="0.25"/>

<xacro:property name="traction_wheel_mass"                value="1"/>
<xacro:property name="traction_wheel_base"                value="0.88"/>
<xacro:property name="traction_wheel_torque"              value="20000"/>
<xacro:property name="traction_wheel_friction"            value="5.0"/>

<xacro:property name="trolley_wheel_mass"                 value="0.1"/>
<xacro:property name="trolley_wheel_base"                 value="0.54"/>
<xacro:property name="trolley_wheel_friction"             value="0.0"/>
<xacro:property name="trolley_wheel_radius"               value="0.06"/>
<!-- a small constant -->
<xacro:property name="eps"                                value="0.002"/>

<xacro:property name="traction_wheel_radius"              value="0.1"/>
<xacro:property name="traction_wheel_width"               value="0.05"/>
<xacro:property name="traction_wheel_base"                value="0.8"/>

<xacro:arg      name="two_d_lidar_enabled"                default="false" />
<xacro:property name="two_d_lidar_update_rate"            value="30"/>
<xacro:property name="two_d_lidar_sample_size"            value="361"/>
<xacro:property name="two_d_lidar_min_angle"              value="0"/>
<xacro:property name="two_d_lidar_max_angle"              value="360"/>
<xacro:property name="two_d_lidar_min_range"              value="0.1"/>
<xacro:property name="two_d_lidar_max_range"              value="16"/>

<xacro:arg      name="camera_enabled"                 		default="false" />
<xacro:property name="camera_baseline"                		value="0.06"/>
<xacro:property name="camera_height"                  		value="0.10"/>
<xacro:property name="camera_horizontal_fov"         	 		value="60"/>

<!-- ............................... LOAD MACROS ................................. -->

<xacro:include filename="$(find new_bcr_robot)/urdf/materials.xacro"/>
<xacro:include filename="$(find new_bcr_robot)/urdf/macros.xacro"/>
<xacro:include filename="$(find new_bcr_robot)/urdf/gazebo.xacro"/>

<!-- ................................ BASE LINK .................................. -->

<link name="base_link"/>

<link name="chassis_link">

	<collision>
		<origin xyz="0 0 0" rpy="0 0 0" />
  		<geometry>
			<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
  		</geometry>
	</collision>

	<visual>
		<origin xyz="0 0 -0.08" rpy="0 0 0" />
  		<geometry>
    		<mesh filename="package://new_bcr_robot/meshes/bcr_chassis.dae" scale="0.1 0.1 0.1"/>
  		</geometry>
	</visual>

	<inertial>
		<mass value="${chassis_mass}" />
		<xacro:box_inertia m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z = "${chassis_height}"/>
	</inertial>

</link>

<joint name="chassis_joint" type="fixed">
	<parent link="base_link"/>
	<child link="chassis_link"/>
	<origin xyz="0.0 0 0.0" rpy="0 0 0.0" />
</joint>

<!-- ................................ WHEELS ..................................... -->

<xacro:trolley_wheel cardinality="front" dexterity="left"  origin_x="${chassis_length/2}" origin_y="${trolley_wheel_base/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>
<xacro:trolley_wheel cardinality="front" dexterity="right" origin_x="${chassis_length/2}" origin_y="-${trolley_wheel_base/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>

<xacro:trolley_wheel cardinality="back" dexterity="left"  origin_x="-${chassis_length/2}" origin_y="${trolley_wheel_base/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>
<xacro:trolley_wheel cardinality="back" dexterity="right" origin_x="-${chassis_length/2}" origin_y="-${trolley_wheel_base/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>

<xacro:traction_wheel cardinality="middle" dexterity="left"  origin_x="0" origin_y="${traction_wheel_base/2}" origin_z="-${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}"/>
<xacro:traction_wheel cardinality="middle" dexterity="right" origin_x="0" origin_y="-${traction_wheel_base/2}" origin_z="-${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}"/>

<!-- ............................. 2D LIDAR ........................................ -->

<xacro:if value="$(arg two_d_lidar_enabled)">

    <link name="two_d_lidar">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
           <cylinder length="0.06" radius="0.075"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
           <cylinder length="0.06" radius="0.075"/>
          </geometry>
          <material name="orange"/>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <mass value="0.1"/>
          <xacro:cylinder_inertia m="0.1" r="0.075" h="0.06"/>
        </inertial>
   </link>

   <joint name="two_d_lidar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="two_d_lidar"/>
      <origin xyz="0.3 0 0.2" rpy="0 0 ${-pi/2}" />
    </joint>

   <gazebo reference="two_d_lidar">
       <material>Gazebo/Orange</material>
   </gazebo>

</xacro:if>

<!-- ............................. CAMERA ........................................ -->

<xacro:if value="$(arg camera_enabled)">

	<!-- KINECT CAMERA -->

	<link name="kinect_camera">

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.07 0.3 0.09"/>
				</geometry>
		</collision>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<mesh filename="package://new_bcr_robot/meshes/kinect/d415.dae"/>
				</geometry>
				<material name="black"/>
		</visual>

		<inertial>
				<mass value="0.01"/>
				<xacro:box_inertia m="0.01" x="0.07" y="0.3" z = "0.09"/>
		</inertial>

	</link>

	<joint name="kinect_camera_joint" type="fixed">
			<origin rpy="0 0 0" xyz="${chassis_length/2} 0 ${chassis_height/4}"/>
			<parent link="base_link"/>
			<child link="kinect_camera"/>
	</joint>

	<link name="kinect_camera_optical"/>

	<joint name="kinect_camera_optical_joint" type="fixed">
		<origin xyz="0 0 0" rpy="-${pi/2} 0 -${pi/2}"/>
		<parent link="kinect_camera"/>
		<child link="kinect_camera_optical"/>
	</joint>

</xacro:if>

<!-- ......................................................................... -->

</robot>
